config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'application#angularHome'
  resources :contacts do
    collection do
      get :rudrabhishekam_list
      get :get_all_contacts
    end
  end
  resources :events

  get "*path" => redirect("/")

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  #attr_accessible :city, :membership, :mobile_num, :name,:email, :status
  
  validates :mobile_num, uniqueness: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  #attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery

  respond_to  :html,:json
  #protect_from_forgery #with: :exception
  #before_action :configure_permitted_parameters, if: :devise_controller?

  after_filter :set_csrf_cookie_for_ng
  def angularHome
    render 'layouts/application'
  end

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  protected

  def verified_request?
    super || form_authenticity_token == request.headers['X-XSRF-TOKEN']
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.json
  before_filter :authenticate_user!, :except => [:new]
  #before_action :authenticate_user!#, :except => [:new]

  def index
    @contacts = Contact.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: {odata: @contacts }}
    end
  end

  def get_all_contacts
    @contacts = Contact.all
    render json: {results: @contacts }
  end
  
  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    @contact.status  = current_user ? "Active" : "New"
    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])
    respond_to do |format|
      if @contact.update_attributes(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render json: @contact }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_path }
      format.json { head :no_content }
    end
  end
  
  
  private
    # Using a private method to encapsulate the permissible parameters is
    # just a good pattern since you'll be able to reuse the same permit
    # list between create and update. Also, you can specialize this method
    # with per-user checking of permissible attributes.
    def contact_params
      params.require(:contact).permit(:city, :membership, :mobile_num, :name,:email, :status)
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   # load_and_authorize_resource
  before_filter :authenticate_user!, :except => [ :auth_token ]
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= form_for @contact , :html => {:multipart => true , :class => "contactForm"} do |f| %>
<% if @contact.errors.any? %>
<div class="form_errors" id="error_explanation">
	<h4><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h4>

	<ul>
		<% @contact.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="formRow">
	<label>Name <span class="redStar">*</span></label>
	<div class="formInputWrap">
		<%= f.text_field :name , :required=> "true"%>
	</div>
</div>
<div class="formRow">
	<label>Email (To Receive Updates)</label>
	<div class="formInputWrap">
		<%= f.text_field :email%>
	</div>
</div>
<div class="formRow">
	<label>Mobile Number <span class="redStar">*</span></label>
	<div class="formInputWrap">
		<%= f.text_field :mobile_num , :class=>"number" , :required=> "true"%>
	</div>

</div>

<% if !f.object.status.blank? %>
<div class="formRow">
	<label>Status <span class="redStar">*</span></label>
	<div class="formInputWrap">
		<%= f.select :status, options_for_select([["New","new" ], ["Active", "Active"],["Disabled","Disabled" ]], @contact.status), :class=>"required" %>
	</div>
</div>
<%end%>

<div class="formRow">
	<label>City of Residence<span class="redStar">*</span></label>
	<div class="formInputWrap">
		<%= f.text_field :city, :class=>"required" %>
	</div>

</div>
<div class="formRow">
	<label>Membership <span class="redStar">*</span></label>
	<div class="formInputWrap">
		<%= f.select :membership, options_for_select([["Member","Member" ],["Not Available","Not Available" ], ["Not a Member", "Not a Member"]], @contact.membership), :class=>"required" %>
	</div>

</div>
<div class="formRow">
	<%= f.submit :class => "floatRight btn btn-success"%>
</div>
<% end %>

<script>
	$(document).ready(function() {
		console.log("here");
		$("#new_contact").validate({

			rules : {
				"contact[mobile_num]" : {
					required : true,
					maxlength : 10,
					minlength : 10
				},
				"contact[email]" : {
					email : true
				}
			}
		});

	}); 
</script>

app/views/contacts/edit.html.erb
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.js"></script>
<div>
	<h3 class="m_t_10 center">Editing Contact</h3>
	<%= render 'form' %>
</div>

app/views/contacts/index.html.erb
<div class="contactContent">
	<table id="contactsTable" class="cell-border" cellspacing="0" width="95%">
		<thead>
			<tr>
				<th>Name</th>
				<th>Mobile num</th>
				<th>Status</th>
				<th>City</th>
				<th>Membership</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>

		</tbody>
	</table>
	<br />
</div>

<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.3/css/jquery.dataTables.css">

<script>
	$(document).ready(function() {
		$('#contactsTable').DataTable({
			"lengthMenu": [[10, 25, 40], [10, 25, 40]],
			ajax :  "/get_all_contacts.json",
			dom : "lf<t>p",
			jqueryUi : true,
			pagination : "full_numbers",
			"columns" : [{
				"data" : "name"
			}, {
				"data" : "mobile_num"
			}, {
				"data" : "status"
			}, {
				"data" : "city"
			}, {
				"data" : "membership"
			}, {
				render : function(data, type, row) {
					return '<a href="/contacts/' + row.id + '">Show</a>'
				}
			}, {
				render : function(data, type, row) {
					return '<a href="/contacts/' + row.id + '/edit">Edit</a>'
				}
			}, {
				render : function(data, type, row) {
					return '<a  data-method="delete" data-confirm="Are you sure?" href="/contacts/' + row.id + '">Destroy</a>'
				}
			}]

		});

	}); 
</script>

app/views/contacts/new.html.erb
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.js"></script>
<div>
	<h3 class="m_t_10 center">New Registration</h3>

	<%= render 'form' %>

</div>

<br/>
<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<% if  notice %>
<p class="alert alert-info" id="notice">
	<%= notice %>
</p>
<%end%>

<table id="contactsTable" class="table table-bordered table-striped showContactTable" cellspacing="0">

	<tbody>
		<tr>
			<td>Name:</td>
			<td><%= @contact.name %></td>
		</tr>
		<tr>
			<td>Mobile Num:</td>
			<td><%= @contact.mobile_num %></td>
		</tr>
		<tr>
			<td>Email</td>
			<td><%= @contact.email %></td>
		</tr>
		<tr>
			<td>Status:</td>
			<td><%= @contact.status %></td>
		</tr>
		<tr>
			<td>City</td>
			<td><%= @contact.city %></td>
		</tr>
		<tr>
			<td>Membership</td>
			<td><%= @contact.membership %></td>
		</tr>

	</tbody>
</table>
<% if current_user %>
<div class="formRow">
	<%= link_to 'Edit', edit_contact_path(@contact) %> |
	<%= link_to 'Back', contacts_path %>
</div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">
<html  ng-app="app" lang="en">
	<head>
		<base href="/">
		<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
		<title>Sample App</title>
		<link rel="shortcut icon" href="favicon.ico">
		<%= csrf_meta_tag %>
		<%= stylesheet_link_tag   "application" ,:media => "all" %>
		<%= javascript_include_tag "application" %>
	</head>

	<body style="background-color:white">
		<br>
		<div id="main">
			<div class="mainContent">
				<div class="collapse navbar-collapse pull-right" ng-controller="NavCtrl">
					<ul class="nav navbar-nav">

						<li ng-hide="signedIn()">
							<a href="/" class="but1" title="">Home1</a>
						</li>
						<li ng-hide="signedIn()">
							<a href="login">Log In</a>
						</li>
						<li ng-hide="signedIn()">
							<a href="register">Register</a>
						</li>
						<li ng-show="signedIn()">
							<a ng-bind="user.email" href="/"></a>
						</li>
						<li ng-show="signedIn()">
							<a ng-click="logout()">Log Out</a>
						</li>
						<li ng-show="signedIn()">
							<a href="/contacts">Contacts Home</a>
						</li>
						<li ng-show="signedIn()">
							<a href="/contacts/new">New Contact</a>
						</li>
						<li ng-show="signedIn()">
							<a href="/contacts">Contacts Home</a>
						</li>
					</ul>
				</div>
				<div class="clearAll"></div>

				<div ng-view ></div>
			</div>
		</div>

	</body>
</html>